name: smoke-windows-strawberryperl

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Find out environment
        shell: cmd
        run: |
          dir c:\Strawberry
          path
          perl -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{gcc})"
          perl -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{g++})"
          perl -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{ld})"
      - name: Configure
        shell: cmd
        run: |
            perl Makefile.PL
      - name: Build
        shell: cmd
        run: |
            make
      - name: Run Tests
        shell: cmd
        run: |
            make test
